name: medical_event_recorder
description: Medical Event Recorder
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4
  uuid: ^4.4.2
  intl: ^0.20.2
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  cross_file: ^0.3.4+2
  file_selector: ^1.0.3
  msix: ^3.16.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/splash_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/app_icon.png
  windows:
    generate: true
    image_path: assets/app_icon.png
    icon_size: 48

flutter_native_splash:
  color: "#0D4F82"
  image: assets/splash_logo.png
  android: true
  ios: true
  web: false

msix_config:
  display_name: Medical Event Recorder
  publisher_display_name: Medical Event Recorder
  identity_name: MedicalEventRecorder
  publisher: CN=MedicalEventRecorder
  msix_version: 1.0.0.0
  logo_path: windows/runner/resources/app_icon.ico
  create_assets: false
  signing_certificate_path: C:/Users/wjl25/Documents/MedicalEventRecorder.pfx
  signing_certificate_password: YOUR_PASSWORD_HERE